# Welcome to Nubia Jekyll Theme!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

theme_version: 1.0.4

# Site settings
lang: es_ES
title: Bridge
name: Chiven Young
title_home: Lenin Peña
logo: # Logo image URL
description: Blogger Tecnológico y Diseñador Web, escribo artículos sobre Internet, Aplicaciones, Diseño y Desarrollo Web, trucos y tips sobre Tecnologías
baseurl: '' # The subpath of your site, e.g. /blog
url: 'https://www.leninalbertop.com.ve' # The base hostname & protocol for your site

twitter:
  username: leninalbertop

facebook: leninblogger

instagram: leninalbertop

github: leninalbertolp

markdown: kramdown
highlighter: rouge
permalink: /:title
paginate: 11

plugins:
  - jekyll-paginate
  - jekyll/tagging
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

include:
  - _pages
  - _redirects
  - .well-known

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE

# SCSS Config
sass:
  style: compressed # possible values: nested expanded compact compressed

# SiteMap Plugin
# defaults:
#   - scope:
#       path: 'tag'
#     values:
#       sitemap: false

# Jekyll Feed Plugin
feed:
  categories:
  - aplicaciones
  - desarrollo-web
  - internet

# Jekyll seo tag config
facebook:
  app_id: 411587729616994

# Tags
tag_page_dir: tag
tag_page_layout: tag_page
tag_permalink_style: pretty

# Pages path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext

# Authors
authors:
  leninalbertop:
    name: Chiven Young
    bio: Blogger Tecnológico y Diseñador Web, me apasiona las tecnologías en general, amante del Open Source.
    gravatar: /images/template/leninalbertop-avatar-autor.webp  #https://s.gravatar.com/avatar/f83141edd9e6339e678648596a403fd5?s=150
    picture: /images/template/leninalbertop-avatar-autor.webp
    email: leninalbertop@outlook.com
    facebook: leninblogger
    github: leninalbertolp
    twitter: leninalbertop
    pinterest: leninalbertop